{
    'name': 'TechFlex TT Complete Website',
    'summary': 'Complete TechFlex TT branded Odoo 19 website and eCommerce design',
    'description': 'Complete TechFlex TT branded website for Odoo 19 with native shop/product inheritance, rental and contact workflows, editable content, and product warranty/specification fields.',
    'version': '19.0.1.2.0',
    'category': 'Website/Website',
    'author': 'Spxcorp Limited',
    'maintainer': 'Spxcorp Limited',
    'website': 'https://techflextt.com',
    'license': 'LGPL-3',
    'depends': ['website_sale', 'mail'],
    "data": [
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/default_content.xml',
        'views/backend_menus.xml',
        'views/rental_request_views.xml',
        'views/contact_request_views.xml',
        'views/team_member_views.xml',
        'views/location_views.xml',
        'views/product_views.xml',
        'views/website_layout.xml',
        'views/website_pages.xml',
        'views/website_sale_templates.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
